# Generated by Django 4.1.2 on 2022-10-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverbyskyline', '0002_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-added']},
        ),
        migrations.AddField(
            model_name='video',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
